cfg:
  unet_config:
    n_filters_init: 16
    depth: 4
    spatial_dims: 2
    in_channels: 1
    out_channels: 4
    num_res_units: 4
    lr: 0.001
    patience: 5
    clue_softmax_t: 1
    batch_size: 32
    binary_target: false
  binary_target: false
  lr: 0.001
  patience: 5
  adapt_num_epochs: 100
  cluster_type: centroids
  clue_softmax_t: 0.1
  dataset:
    data_dir: /home/mikhelson/MedImSeg-Lab24/data/MNM/
    vendor_assignment:
      train: siemens
      test: ge
    batch_size: 32
    binary_target: false
    non_empty_target: false
  unet:
    n_filters_init: 16
    depth: 4
    spatial_dims: 2
    in_channels: 1
    out_channels: 4
    num_res_units: 4
    lr: 0.001
    patience: 5
    clue_softmax_t: 1
    batch_size: 32
    binary_target: false
  trainer:
    train_transforms: global_transforms
    limit_train_batches: 50
    max_epochs: 100
    early_stopping:
      monitor: val_loss
      mode: min
    model_checkpoint:
      save_top_k: 2
      dirpath: ../../MedImSeg-Lab24/pre-trained/trained_UNets
      monitor: val_loss
    logging: true
